export const EVENTS_DATA = [
  {
    id: 1,
    title: "Brews & Beats: Coffee Rave",
    host: "Hyperliquid Philippines",
    description: "Experience the ultimate caffeine-fueled dance party. Join us for a night of artisanal blends and electrifying beats.",
    longDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Brews & Beats is not just a party; it's a movement. We bring together the best baristas and DJs for a sensory experience like no other. Expect free-flowing espresso martinis, latte art competitions, and a bass-heavy lineup that keeps you moving until sunrise.",
    date: "Dec 10-15, 2025",
    time: "8:00 PM - 3:00 AM",
    location: "Taguig City, Metro Manila",
    venue: "The Roastery Warehouse",
    attendees: 3247,
    capacity: 5000,
    image: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=1200",
    category: "Music",
    status: "upcoming"
  },
  {
    id: 2,
    title: "Neon Nights: Art Gallery",
    host: "Azend Official",
    description: "Immersive digital art exhibition with live synthwave. Walk through tunnels of light and sound.",
    longDescription: "Step into the future at Neon Nights. Featuring 20+ digital artists from around the globe, this exhibition blurs the line between the physical and virtual worlds. Interactive installations allow you to become part of the art.",
    date: "Jan 20, 2026",
    time: "6:00 PM - 10:00 PM",
    location: "BGC Arts Center",
    venue: "Main Gallery",
    attendees: 1500,
    capacity: 2000,
    image: "https://images.unsplash.com/photo-1544531586-fde5298cdd40?q=80&w=1200",
    category: "Art",
    status: "upcoming"
  },
  {
    id: 3,
    title: "Rock Festival 2025",
    host: "Red Horse Prod",
    description: "The loudest rock event of the year.",
    longDescription: "Prepare for ear-shattering riffs and mosh pits. Rock Festival 2025 gathers the legends of rock and the rising stars of metal on one massive stage.",
    date: "Nov 28, 2025",
    time: "4:00 PM - 12:00 AM",
    location: "Taguig City, Metro Manila",
    venue: "Open Grounds",
    attendees: 3247,
    capacity: 5000,
    image: "https://images.unsplash.com/photo-1459749411177-2a29658bbc64?q=80&w=1200",
    category: "Music",
    status: "upcoming"
  },
  {
    id: 4,
    title: "Fashion Week: Runway",
    host: "Vogue PH",
    description: "Exclusive look at the 2026 Summer Collection.",
    longDescription: "Witness high fashion up close. Top designers showcase their sustainable summer collections in an exclusive runway event.",
    date: "Feb 14, 2026",
    time: "7:00 PM - 11:00 PM",
    location: "Okada Manila",
    venue: "Grand Ballroom",
    attendees: 800,
    capacity: 1000,
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=1200",
    category: "Fashion",
    status: "upcoming"
  },
  {
    id: 5,
    title: "Cyberpunk Cosplay Expo",
    host: "Cosplay Mania",
    description: "Costume contest and gaming convention.",
    longDescription: "Suit up, Samurai. The biggest cyberpunk-themed convention is here. Prizes for best costume, gaming tournaments, and tech demos.",
    date: "Mar 05, 2026",
    time: "10:00 AM - 8:00 PM",
    location: "Pasay City",
    venue: "SMX Convention Center",
    attendees: 5000,
    capacity: 8000,
    image: "https://images.unsplash.com/photo-1560419015-7c427e8ae5ba?q=80&w=1200",
    category: "Gaming",
    status: "upcoming"
  }
];